"""
Build script generator - Generates Windows batch scripts for Qt build
"""

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..config.schema import InstallConfig
    from .env_setup import EnvironmentManager


def generate_build_script(
    config: "InstallConfig",
    env_manager: "EnvironmentManager",
    build_dir: Path
) -> Path:
    """
    Generate Windows batch script for building Qt.
    This avoids environment variable inheritance issues with subprocess.

    Args:
        config: Installation configuration
        env_manager: Environment manager
        build_dir: Build directory path

    Returns:
        Path to generated batch script
    """
    import sys
    import os

    env = env_manager.get_build_environment()

    # Get paths
    mingw_bin = env.get("MINGW_ROOT", "")
    perl_bin = env.get("PERL_ROOT", "")
    python_bin = env.get("PYTHON_ROOT", "")
    llvm_bin = str(config.harmony_sdk_path / "native" / "llvm" / "bin")

    # If python_bin not set, try multiple fallback sources
    if not python_bin:
        # First try from config
        if config.python_path:
            from pathlib import Path as PPath
            python_path = PPath(config.python_path)
            if python_path.is_file():
                python_bin = str(python_path.parent)
            elif python_path.name.lower() == "bin":
                python_bin = str(python_path)
            else:
                python_bin = str(python_path / "bin")

        # Second fallback: use current Python executable directory
        if not python_bin:
            python_bin = os.path.dirname(sys.executable)

    # Configure script path
    configure_script = config.qt_source_path / "configure.bat"

    # Build configure arguments
    device_prefix = f"/data/storage/el1/bundle/libs/{config.architecture.split('-')[0]}"

    # Get version-specific configuration for skip_modules
    from ..config.defaults import get_qt_version_config
    version_config = get_qt_version_config(config.qt_version)
    skip_modules_list = config.skip_modules if config.skip_modules else version_config.get("skip_modules", [])
    skip_modules = " ".join([f"-skip {m}" for m in skip_modules_list])

    # Get extra configure options
    extra_options = version_config.get("extra_configure_options", [])
    extra_args = " ".join(extra_options)

    cxx_std = version_config.get("c++std", "c++14")

    # Build type option
    build_type_opt = "-debug" if config.build_type == "debug" else "-release"

    # Generate script content
    script_content = f'''@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

echo ============================================
echo Qt for HarmonyOS Build Script
echo Qt Version: {config.qt_version}
echo Generated by qtohos-installer
echo ============================================
echo.

REM Reset PATH to avoid MSVC pollution and other MinGW interference
set "PATH=C:\\Windows\\System32;C:\\Windows"

REM Clear MAKEFLAGS to prevent sh.exe dependency from other MinGW
set "MAKEFLAGS="
set "MFLAGS="
set "SHELL=cmd.exe"

REM Add llvm-mingw-ucrt FIRST
set "MINGW_BIN={mingw_bin}"
if exist "%MINGW_BIN%" set "PATH=%PATH%;%MINGW_BIN%"
if exist "%MINGW_BIN%" echo [OK] MinGW (llvm-mingw): %MINGW_BIN%
if not exist "%MINGW_BIN%" echo [ERROR] MinGW path not found: %MINGW_BIN%
if not exist "%MINGW_BIN%" exit /b 1

REM Add Perl
set "PERL_BIN={perl_bin}"
if exist "%PERL_BIN%" set "PATH=%PATH%;%PERL_BIN%"
if exist "%PERL_BIN%" echo [OK] Perl: %PERL_BIN%
if not exist "%PERL_BIN%" echo [ERROR] Perl path not found: %PERL_BIN%
if not exist "%PERL_BIN%" exit /b 1

REM Add Python for QML compilation
set "PYTHON_BIN={python_bin}"
if exist "%PYTHON_BIN%" set "PATH=%PATH%;%PYTHON_BIN%"
if exist "%PYTHON_BIN%" echo [OK] Python: %PYTHON_BIN%"
if not exist "%PYTHON_BIN%" echo [WARN] Python path not configured - using system Python

REM Add LLVM for OHOS cross-compile
set "LLVM_BIN={llvm_bin}"
if exist "%LLVM_BIN%" set "PATH=%PATH%;%LLVM_BIN%"
if exist "%LLVM_BIN%" echo [OK] LLVM: %LLVM_BIN%
if not exist "%LLVM_BIN%" echo [WARN] LLVM path not found: %LLVM_BIN%

REM Set environment variables
set "NATIVE_OHOS_SDK={config.harmony_sdk_path}\\native"
set "OHOS_SDK_SYSROOT={config.harmony_sdk_path}\\native\\sysroot"
set "LLVM_INSTALL_DIR={llvm_bin}\\.."
set "OHOS_SDK_ROOT={config.harmony_sdk_path}"
set "OHOS_TARGET_ARCH={config.architecture}"

echo.
echo Environment:
echo   NATIVE_OHOS_SDK: %NATIVE_OHOS_SDK%
echo   OHOS_TARGET_ARCH: %OHOS_TARGET_ARCH%
echo.

REM Compiler check
where cl.exe >nul 2>&1
if %errorlevel% equ 0 echo [WARN] MSVC cl.exe found in PATH - may cause issues
if %errorlevel% neq 0 echo [OK] MSVC cl.exe not found

REM Unset compiler environment variables
set "QMAKESPEC="
set "XQMAKESPEC="
set "QMAKEPATH="
set "QMAKEFEATURES="

echo.
echo ============================================

REM Create build directory
set "BUILD_DIR={build_dir}"
if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"

REM Run configure
echo.
echo [Configure] Starting...
echo.

pushd "%BUILD_DIR%"

call "{configure_script}" -v -platform win32-clang-g++ -xplatform ohos-clang -device-option CROSS_COMPILE=%LLVM_INSTALL_DIR%\\bin -prefix "{device_prefix}" -extprefix "{config.install_path}" -opensource -confirm-license {build_type_opt} -no-use-gold-linker {skip_modules} {extra_args} -nomake tests -nomake examples -no-gcc-sysroot -c++std {cxx_std} -ohos-arch {config.architecture}

if %errorlevel% neq 0 echo.
if %errorlevel% neq 0 echo [ERROR] Configure failed with code %errorlevel%
if %errorlevel% neq 0 popd
if %errorlevel% neq 0 exit /b 1

echo.
echo [OK] Configure completed successfully
echo.

REM Build
echo [Build] Starting with {config.parallel_jobs} parallel jobs...
echo.

set "SHELL=cmd.exe"
mingw32-make SHELL=cmd.exe -j{config.parallel_jobs}

if %errorlevel% neq 0 echo.
if %errorlevel% neq 0 echo [ERROR] Build failed with code %errorlevel%
if %errorlevel% neq 0 popd
if %errorlevel% neq 0 exit /b 1

echo.
echo [OK] Build completed successfully
echo.

REM Install
echo [Install] Starting...
echo.

mingw32-make install

if %errorlevel% neq 0 echo.
if %errorlevel% neq 0 echo [ERROR] Install failed with code %errorlevel%
if %errorlevel% neq 0 popd
if %errorlevel% neq 0 exit /b 1

popd

REM Copy runtime DLLs
echo.
echo [Copy] Copying runtime dependencies...
for %%d in (libstdc++-6.dll libgcc_s_seh-1.dll libwinpthread-1.dll) do if exist "%MINGW_BIN%\\%%d" copy /y "%MINGW_BIN%\\%%d" "{config.install_path}\\bin\\" >nul

echo.
echo ============================================
echo [SUCCESS] Build completed!
echo Install path: {config.install_path}
echo ============================================

if exist "{config.install_path}\\bin\\qmake.exe" echo.
if exist "{config.install_path}\\bin\\qmake.exe" echo Qt version:
if exist "{config.install_path}\\bin\\qmake.exe" "{config.install_path}\\bin\\qmake.exe" -query QT_VERSION

exit /b 0
'''

    # Write script to file
    script_path = build_dir.parent / "build_qt_ohos.bat"
    script_path.write_text(script_content, encoding="utf-8")

    return script_path