"""
Qt builder module
"""

import os
import sys
import shutil
import tempfile
from pathlib import Path
from typing import List, Optional, Tuple
import logging
from rich.console import Console
from rich.panel import Panel

from .config import InstallConfig
from .environment import EnvironmentManager
from .utils import run_command, ensure_directory, is_windows


class QtBuilder:
    """Build Qt for HarmonyOS"""

    def __init__(
        self,
        config: InstallConfig,
        env_manager: EnvironmentManager,
        logger: Optional[logging.Logger] = None
    ):
        self.config = config
        self.env_manager = env_manager
        self.logger = logger or logging.getLogger("qtohos-installer")
        self.console = Console()

        # Build directory (parallel to source dir, per Qt HarmonyOS wiki)
        self.build_dir = config.qt_source_path.parent / f"build_{config.architecture}"

        # Make command
        self.make_cmd = "mingw32-make" if is_windows() else "make"

        # Script path for Windows batch script
        self.build_script_path: Optional[Path] = None
    
    def prepare_build_directory(self) -> bool:
        """
        Prepare build directory

        Returns:
            True if successful, False otherwise
        """
        self.console.print("\n[bold cyan]Preparing build directory...[/bold cyan]")

        try:
            # Create build directory
            ensure_directory(self.build_dir)

            self.console.print(f"[green]✓ Build directory created: {self.build_dir}[/green]")
            return True

        except Exception as e:
            self.console.print(f"[red]✗ Failed to create build directory: {e}[/red]")
            self.logger.error(f"Failed to create build directory: {e}")
            return False

    def generate_build_script(self) -> Path:
        """
        Generate Windows batch script for building Qt.
        This avoids environment variable inheritance issues with subprocess.

        Returns:
            Path to generated batch script
        """
        env = self.env_manager.get_build_environment()

        # Get paths
        mingw_bin = env.get("MINGW_ROOT", "")
        perl_bin = env.get("PERL_ROOT", "")
        llvm_bin = str(self.config.harmony_sdk_path / "native" / "llvm" / "bin")

        # Determine configure script
        qtbase_configure = self.config.qt_source_path / "qtbase" / "configure.bat"
        if qtbase_configure.exists():
            configure_cmd = f'call "{qtbase_configure}" -top-level'
        else:
            configure_cmd = f'call "{self.config.qt_source_path}\\configure.bat"'

        # Build configure arguments
        device_prefix = f"/data/storage/el1/bundle/libs/{self.config.architecture.split('-')[0]}"
        skip_modules = " ".join([f"-skip {m}" for m in self.config.skip_modules])

        # Generate script content
        script_content = f'''@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

echo ============================================
echo Qt for HarmonyOS Build Script
echo Generated by qtohos-installer
echo ============================================
echo.

:: Reset PATH to avoid MSVC pollution
set "PATH=C:\\Windows\\System32;C:\\Windows"

:: Add MinGW
set "MINGW_BIN={mingw_bin}"
if exist "%MINGW_BIN%" (
    set "PATH=%PATH%;%MINGW_BIN%"
    echo [OK] MinGW: %MINGW_BIN%
) else (
    echo [ERROR] MinGW path not found: %MINGW_BIN%
    exit /b 1
)

:: Add Perl
set "PERL_BIN={perl_bin}"
if exist "%PERL_BIN%" (
    set "PATH=%PATH%;%PERL_BIN%"
    echo [OK] Perl: %PERL_BIN%
) else (
    echo [ERROR] Perl path not found: %PERL_BIN%
    exit /b 1
)

:: Add LLVM
set "LLVM_BIN={llvm_bin}"
if exist "%LLVM_BIN%" (
    set "PATH=%PATH%;%LLVM_BIN%"
    echo [OK] LLVM: %LLVM_BIN%
) else (
    echo [WARN] LLVM path not found: %LLVM_BIN%
)

:: Set environment variables
set "NATIVE_OHOS_SDK={self.config.harmony_sdk_path}\\native"
set "OHOS_SDK_SYSROOT={self.config.harmony_sdk_path}\\native\\sysroot"
set "LLVM_INSTALL_DIR={llvm_bin}\\.."
set "OHOS_SDK_ROOT={self.config.harmony_sdk_path}"
set "OHOS_TARGET_ARCH={self.config.architecture}"

:: NOTE: Do NOT set QMAKESPEC before configure - Qt will detect it automatically
:: Setting QMAKESPEC before configure causes: "Please make sure to unset QMAKESPEC"

echo.
echo Environment:
echo   NATIVE_OHOS_SDK: %NATIVE_OHOS_SDK%
echo   OHOS_TARGET_ARCH: %OHOS_TARGET_ARCH%
echo.

:: Check compilers
echo Compiler check:
where cl.exe >nul 2>&1
if %errorlevel% equ 0 (
    echo [WARN] MSVC cl.exe found in PATH - may cause issues
) else (
    echo [OK] MSVC cl.exe not found
)

where gcc.exe >nul 2>&1
if %errorlevel% equ 0 (
    echo [OK] GCC found
) else (
    echo [ERROR] GCC not found
    exit /b 1
)

:: Unset Qt environment variables that should not be set before configure
set "QMAKESPEC="
set "XQMAKESPEC="
set "QMAKEPATH="
set "QMAKEFEATURES="

echo.
echo ============================================

:: Create build directory
set "BUILD_DIR={self.build_dir}"
if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"

:: Clean config.tests
if exist "D:\\code\\config.tests" rd /s /q "D:\\code\\config.tests"

:: Run configure
echo.
echo [Configure] Starting...
echo.

pushd "%BUILD_DIR%"

{configure_cmd} -v -platform win32-g++ -xplatform ohos-clang -device-option OHOS_ARCH={self.config.architecture} -opensource -confirm-license -no-use-gold-linker -no-gcc-sysroot -opengl es2 -opengles3 -c++std c++14 -nomake examples -nomake tests -release -prefix "{device_prefix}" -extprefix "{self.config.install_path}" -no-dbus -make-tool "mingw32-make -j{self.config.parallel_jobs}" -recheck-all {skip_modules}

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Configure failed with code %errorlevel%
    popd
    exit /b 1
)

echo.
echo [OK] Configure completed successfully
echo.

:: Build
echo [Build] Starting with {self.config.parallel_jobs} parallel jobs...
echo.

mingw32-make -j{self.config.parallel_jobs}

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Build failed with code %errorlevel%
    popd
    exit /b 1
)

echo.
echo [OK] Build completed successfully
echo.

:: Install
echo [Install] Starting...
echo.

mingw32-make install

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Install failed with code %errorlevel%
    popd
    exit /b 1
)

popd

:: Copy runtime DLLs
echo.
echo [Copy] Copying runtime dependencies...
for %%d in (libstdc++-6.dll libgcc_s_seh-1.dll libwinpthread-1.dll) do (
    if exist "%MINGW_BIN%\\%%d" (
        copy /y "%MINGW_BIN%\\%%d" "{self.config.install_path}\\bin\\" >nul
        echo [OK] Copied: %%d
    )
)

echo.
echo ============================================
echo [SUCCESS] Build completed!
echo Install path: {self.config.install_path}
echo ============================================

if exist "{self.config.install_path}\\bin\\qmake.exe" (
    echo.
    echo Qt version:
    "{self.config.install_path}\\bin\\qmake.exe" -query QT_VERSION
)

exit /b 0
'''

        # Write script to file
        script_path = self.build_dir.parent / "build_qt_ohos.bat"
        script_path.write_text(script_content, encoding="utf-8")
        self.build_script_path = script_path

        self.console.print(f"[green]✓ Generated build script: {script_path}[/green]")
        self.logger.info(f"Generated build script: {script_path}")

        return script_path
    
    def generate_configure_command(self) -> List[str]:
        """
        Generate configure command for Qt
        
        Returns:
            Configure command as list of strings
        """
        self.console.print("\n[bold cyan]Generating configure command...[/bold cyan]")
        
        # Base configure command
        # Prefer qtbase/configure.bat -top-level (same as Qt HarmonyOS wiki and
        # common manual workflows). Fallback to top-level configure script.
        if is_windows():
            qtbase_configure = self.config.qt_source_path / "qtbase" / "configure.bat"
            root_configure = self.config.qt_source_path / "configure.bat"
            if qtbase_configure.exists():
                configure_script = qtbase_configure
                cmd = [str(configure_script), "-top-level"]
            else:
                configure_script = root_configure
                cmd = [str(configure_script)]
        else:
            configure_script = self.config.qt_source_path / "configure"
            cmd = [str(configure_script)]
        
        # Add common options
        cmd.extend([
            "-v",  # Verbose output
        ])

        # CRITICAL: Specify host platform to use MinGW for building host tools
        if is_windows():
            cmd.extend(["-platform", "win32-g++"])

        # Cross-compilation target platform
        cmd.extend(["-xplatform", "ohos-clang"])

        cmd.extend([
            "-opensource",
            "-confirm-license",
            "-no-use-gold-linker",
            "-no-gcc-sysroot",
        ])

        # Qt5 specific: Use -device-option for OHOS architecture
        cmd.extend(["-device-option", f"OHOS_ARCH={self.config.architecture}"])

        # OpenGL configuration for HarmonyOS
        cmd.extend(["-opengl", "es2", "-opengles3"])

        cmd.extend([
            "-c++std", "c++14",
            "-nomake", "examples",
            "-nomake", "tests",
        ])
        
        # Build type
        if self.config.build_type == "debug":
            cmd.append("-debug")
        elif self.config.build_type == "release":
            cmd.append("-release")
        else:  # release-with-debug-info
            cmd.extend(["-release", "-force-debug-info"])
        
        # Installation prefix
        # For HarmonyOS, we use two prefixes:
        # -prefix: location on device (e.g., /data/storage/el1/bundle/libs/arm64)
        # -extprefix: external prefix (actual installation location)
        
        device_prefix = f"/data/storage/el1/bundle/libs/{self.config.architecture.split('-')[0]}"
        cmd.extend([
            "-prefix", device_prefix,
            "-extprefix", str(self.config.install_path),
        ])
        
        # Windows-specific options
        if is_windows():
            llvm_dir = self.env_manager.env_vars.get("LLVM_INSTALL_DIR", "")
            if llvm_dir:
                cmd.extend(["-device-option", f"CROSS_COMPILE={llvm_dir}/bin"])
        
        # Skip modules
        for module in self.config.skip_modules:
            cmd.extend(["-skip", module])
        
        # No DBus (not available on HarmonyOS)
        cmd.append("-no-dbus")

        # Specify make tool for Qt5 (required for proper build)
        cmd.extend(["-make-tool", f"{self.make_cmd} -j{self.config.parallel_jobs}"])

        # Display command
        self.console.print("\n[bold]Configure command:[/bold]")
        cmd_str = " ".join(cmd)
        self.console.print(Panel(cmd_str, border_style="cyan"))
        
        return cmd
    
    def configure_qt(self) -> Tuple[int, str, str]:
        """
        Run Qt configure
        
        Returns:
            Tuple of (exit_code, stdout, stderr)
        """
        self.console.print("\n[bold cyan]Configuring Qt...[/bold cyan]")
        self.logger.info("Starting Qt configuration")
        
        cmd = self.generate_configure_command()
        env = self.env_manager.get_build_environment()
        self._print_windows_path_check(env)
        self._print_compiler_detection(env)

        # Run configure
        exit_code, stdout, stderr = run_command(
            cmd,
            cwd=self.build_dir,
            env=env,
            capture_output=False,
            logger=self.logger
        )
        
        if exit_code == 0:
            self.console.print("\n[green]✓ Qt configuration completed successfully[/green]")
            self.logger.info("Qt configuration completed successfully")
        else:
            self.console.print(f"\n[red]✗ Qt configuration failed with code: {exit_code}[/red]")
            self.logger.error(f"Qt configuration failed with code: {exit_code}")
        
        return exit_code, stdout, stderr

    def _print_windows_path_check(self, env: dict) -> None:
        """
        Print Windows build environment and verify required PATH entries.
        """
        if not is_windows():
            return

        self.console.print("\n[bold cyan]Build environment (Windows) before configure:[/bold cyan]")
        self.console.print(f"  [cyan]MINGW_ROOT[/cyan]: {env.get('MINGW_ROOT', '(not set)')}")
        self.console.print(f"  [cyan]PERL_ROOT[/cyan]: {env.get('PERL_ROOT', '(not set)')}")
        self.console.print(f"  [cyan]QMAKESPEC[/cyan]: {env.get('QMAKESPEC', '(not set)')}")

        path_value = env.get("PATH", "")
        path_entries = [item for item in path_value.split(";") if item]
        normalized_entries = {item.rstrip("\\/").lower() for item in path_entries}

        required_paths: List[Path] = []

        mingw_bin_raw = env.get("MINGW_ROOT")
        if mingw_bin_raw:
            mingw_bin = Path(mingw_bin_raw)
            required_paths.extend([mingw_bin, mingw_bin.parent])

        perl_bin_raw = env.get("PERL_ROOT")
        if perl_bin_raw:
            perl_bin = Path(perl_bin_raw)
            if perl_bin.name.lower() != "bin":
                perl_bin = perl_bin / "bin"
            perl_root = perl_bin.parent
            strawberry_root = perl_root.parent
            required_paths.extend([
                perl_bin,
                strawberry_root / "c" / "bin",
                perl_root / "site" / "bin",
            ])

        # Keep order and remove duplicates.
        deduped_required = []
        seen = set()
        for item in required_paths:
            key = str(item).rstrip("\\/").lower()
            if key and key not in seen:
                seen.add(key)
                deduped_required.append(str(item))

        if deduped_required:
            self.console.print("  [bold]Required PATH entries:[/bold]")
            for item in deduped_required:
                exists_in_path = item.rstrip("\\/").lower() in normalized_entries
                symbol = "[green]✓[/green]" if exists_in_path else "[red]✗[/red]"
                self.console.print(f"    {symbol} {item}")
        else:
            self.console.print("  [yellow]No required Windows tool roots derived from config.[/yellow]")

    def _print_compiler_detection(self, env: dict) -> None:
        """
        Print compiler detection status before configure.

        Verifies that:
        - MSVC cl.exe is NOT in PATH (should not be found)
        - GCC IS in PATH (should be found on Windows)
        - Clang IS in PATH (should be found)
        """
        if not is_windows():
            return

        self.console.print("\n[bold cyan]Compiler detection before configure:[/bold cyan]")

        path_value = env.get("PATH", "")

        # Check for MSVC cl.exe (should NOT be found)
        cl_path = shutil.which("cl.exe", path=path_value)
        if cl_path:
            self.console.print(f"  [red]✗ MSVC cl.exe found (PROBLEM): {cl_path}[/red]")
            self.console.print("    [yellow]This may cause configure to select MSVC instead of MinGW[/yellow]")
        else:
            self.console.print("  [green]✓ MSVC cl.exe not found (correct)[/green]")

        # Check for GCC (SHOULD be found on Windows)
        gcc_path = shutil.which("gcc.exe", path=path_value)
        if gcc_path:
            self.console.print(f"  [green]✓ GCC found: {gcc_path}[/green]")
        else:
            self.console.print("  [red]✗ GCC not found (PROBLEM)[/red]")
            self.console.print("    [yellow]MinGW should be in PATH for building host tools[/yellow]")

        # Check for Clang (SHOULD be found)
        clang_path = shutil.which("clang.exe", path=path_value)
        if clang_path:
            self.console.print(f"  [green]✓ Clang found: {clang_path}[/green]")
        else:
            self.console.print("  [yellow]⚠ Clang not found[/yellow]")
            self.console.print("    [yellow]Clang is needed for cross-compiling to HarmonyOS[/yellow]")

        self.logger.info(
            "Compiler detection - cl.exe: %s, gcc: %s, clang: %s",
            cl_path or "(not found)",
            gcc_path or "(not found)",
            clang_path or "(not found)",
        )

    def build_qt(self) -> Tuple[int, str, str]:
        """
        Build Qt (make)
        
        Returns:
            Tuple of (exit_code, stdout, stderr)
        """
        self.console.print("\n[bold cyan]Building Qt...[/bold cyan]")
        self.console.print(
            f"[yellow]This may take a long time (parallel jobs: {self.config.parallel_jobs})[/yellow]"
        )
        self.logger.info(f"Starting Qt build with {self.config.parallel_jobs} parallel jobs")
        
        env = self.env_manager.get_build_environment()
        self._print_make_tool_path(env)
        
        # Make command
        cmd = [self.make_cmd, f"-j{self.config.parallel_jobs}"]
        
        # Run make
        exit_code, stdout, stderr = run_command(
            cmd,
            cwd=self.build_dir,
            env=env,
            capture_output=False,
            logger=self.logger
        )
        
        if exit_code == 0:
            self.console.print("\n[green]✓ Qt build completed successfully[/green]")
            self.logger.info("Qt build completed successfully")
        else:
            self.console.print(f"\n[red]✗ Qt build failed with code: {exit_code}[/red]")
            self.logger.error(f"Qt build failed with code: {exit_code}")
        
        return exit_code, stdout, stderr
    
    def install_qt(self) -> Tuple[int, str, str]:
        """
        Install Qt (make install)
        
        Returns:
            Tuple of (exit_code, stdout, stderr)
        """
        self.console.print("\n[bold cyan]Installing Qt...[/bold cyan]")
        self.logger.info("Starting Qt installation")
        
        env = self.env_manager.get_build_environment()
        self._print_make_tool_path(env)
        
        # Make install command
        cmd = [self.make_cmd, "install"]
        
        # Run make install
        exit_code, stdout, stderr = run_command(
            cmd,
            cwd=self.build_dir,
            env=env,
            capture_output=False,
            logger=self.logger
        )
        
        if exit_code == 0:
            self.console.print("\n[green]✓ Qt installation completed successfully[/green]")
            self.logger.info("Qt installation completed successfully")
            
            # Verify installation
            self._verify_installation()
        else:
            self.console.print(f"\n[red]✗ Qt installation failed with code: {exit_code}[/red]")
            self.logger.error(f"Qt installation failed with code: {exit_code}")
        
        return exit_code, stdout, stderr

    def _print_make_tool_path(self, env: dict) -> None:
        """Print currently resolved make tool path before running make commands."""
        self.console.print("\n[bold cyan]Resolving make tool...[/bold cyan]")
        configured_make = str(self.config.make_path) if self.config.make_path else "(not configured)"
        resolved_make = shutil.which(self.make_cmd, path=env.get("PATH"))
        self.console.print(f"  [cyan]Configured make_path[/cyan]: {configured_make}")
        self.console.print(f"  [cyan]make command[/cyan]: {self.make_cmd}")
        self.console.print(f"  [cyan]Resolved path[/cyan]: {resolved_make or '(not found in PATH)'}")
        self.logger.info(
            "Make tool resolution - configured: %s, command: %s, resolved: %s",
            configured_make,
            self.make_cmd,
            resolved_make or "(not found in PATH)",
        )
    
    def _verify_installation(self) -> None:
        """Verify Qt installation"""
        self.console.print("\n[bold cyan]Verifying installation...[/bold cyan]")
        
        # Check for qmake
        qmake_path = self.config.install_path / "bin" / "qmake"
        if is_windows():
            qmake_path = qmake_path.with_suffix(".exe")
        
        if qmake_path.exists():
            self.console.print(f"[green]✓ qmake found: {qmake_path}[/green]")
            
            # Get Qt version
            try:
                result = run_command(
                    [str(qmake_path), "-query", "QT_VERSION"],
                    capture_output=True,
                    logger=self.logger
                )
                if result[0] == 0:
                    qt_version = result[1].strip()
                    self.console.print(f"[green]  Qt version: {qt_version}[/green]")
            except Exception:
                pass
        else:
            self.console.print(f"[yellow]⚠ qmake not found at expected location[/yellow]")
        
        # Check for libraries
        lib_dir = self.config.install_path / "lib"
        if lib_dir.exists():
            libs = list(lib_dir.glob("*.so")) if not is_windows() else list(lib_dir.glob("*.dll"))
            self.console.print(f"[green]✓ Found {len(libs)} libraries[/green]")
        else:
            self.console.print(f"[yellow]⚠ Library directory not found[/yellow]")
    
    def build_all(self) -> bool:
        """
        Run complete build process

        Returns:
            True if all steps successful, False otherwise
        """
        self.console.print("\n" + "=" * 60)
        self.console.print("[bold cyan]Starting Qt Build Process[/bold cyan]")
        self.console.print("=" * 60)

        # Step 1: Prepare build directory
        if not self.prepare_build_directory():
            return False

        # On Windows, use batch script to avoid environment inheritance issues
        if is_windows():
            return self._build_with_script()

        # On Unix, use direct subprocess calls
        # Step 2: Configure
        exit_code, _, _ = self.configure_qt()
        if exit_code != 0:
            return False

        # Step 3: Build
        exit_code, _, _ = self.build_qt()
        if exit_code != 0:
            return False

        # Step 4: Install
        exit_code, _, _ = self.install_qt()
        if exit_code != 0:
            return False

        self.console.print("\n" + "=" * 60)
        self.console.print("[bold green]✓ Qt Build Process Completed Successfully[/bold]")
        self.console.print("=" * 60)

        return True

    def _build_with_script(self) -> bool:
        """
        Build Qt using generated batch script (Windows only).
        This avoids environment variable inheritance issues with subprocess.

        Returns:
            True if successful, False otherwise
        """
        self.console.print("\n[bold cyan]Building Qt with batch script (Windows)...[/bold cyan]")

        # Generate the build script
        script_path = self.generate_build_script()

        self.console.print(f"\n[yellow]Running build script: {script_path}[/yellow]")
        self.console.print("[yellow]This may take a long time...[/yellow]")
        self.logger.info(f"Executing build script: {script_path}")

        # Run the batch script
        try:
            # Use subprocess to run the batch script
            # The script handles all environment setup internally
            import subprocess

            result = subprocess.run(
                [str(script_path)],
                cwd=self.build_dir.parent,
                shell=True,
                env=os.environ.copy()  # Pass minimal environment, script will override
            )

            if result.returncode == 0:
                self.console.print("\n" + "=" * 60)
                self.console.print("[bold green]✓ Qt Build Process Completed Successfully[/bold]")
                self.console.print("=" * 60)
                self._verify_installation()
                return True
            else:
                self.console.print(f"\n[red]✗ Build failed with code: {result.returncode}[/red]")
                self.logger.error(f"Build script failed with code: {result.returncode}")
                return False

        except Exception as e:
            self.console.print(f"\n[red]✗ Failed to run build script: {e}[/red]")
            self.logger.error(f"Failed to run build script: {e}")
            return False
