"""
Qt builder module
"""

import os
import sys
import shutil
import tempfile
from pathlib import Path
from typing import List, Optional, Tuple
import logging
from rich.console import Console
from rich.panel import Panel

from .config import InstallConfig
from .environment import EnvironmentManager
from .utils import run_command, ensure_directory, is_windows


class QtBuilder:
    """Build Qt for HarmonyOS"""

    def __init__(
        self,
        config: InstallConfig,
        env_manager: EnvironmentManager,
        logger: Optional[logging.Logger] = None
    ):
        self.config = config
        self.env_manager = env_manager
        self.logger = logger or logging.getLogger("qtohos-installer")
        self.console = Console()

        # Build directory (parallel to source dir, per Qt HarmonyOS wiki)
        self.build_dir = config.qt_source_path.parent / f"build_{config.architecture}"

        # Make command
        self.make_cmd = "mingw32-make" if is_windows() else "make"

        # Script path for Windows batch script
        self.build_script_path: Optional[Path] = None
    
    def prepare_build_directory(self) -> bool:
        """
        Prepare build directory

        Returns:
            True if successful, False otherwise
        """
        self.console.print("\n[bold cyan]Preparing build directory...[/bold cyan]")

        try:
            # Create build directory
            ensure_directory(self.build_dir)

            self.console.print(f"[green]✓ Build directory created: {self.build_dir}[/green]")
            return True

        except Exception as e:
            self.console.print(f"[red]✗ Failed to create build directory: {e}[/red]")
            self.logger.error(f"Failed to create build directory: {e}")
            return False

    def generate_build_script(self) -> Path:
        """
        Generate Windows batch script for building Qt.
        This avoids environment variable inheritance issues with subprocess.

        Returns:
            Path to generated batch script
        """
        env = self.env_manager.get_build_environment()

        # Get paths
        mingw_bin = env.get("MINGW_ROOT", "")
        perl_bin = env.get("PERL_ROOT", "")
        llvm_bin = str(self.config.harmony_sdk_path / "native" / "llvm" / "bin")

        # Determine configure script - use top-level configure for proper -skip support
        configure_script = self.config.qt_source_path / "configure.bat"

        # Build configure arguments - use -ohos-arch for all versions
        device_prefix = f"/data/storage/el1/bundle/libs/{self.config.architecture.split('-')[0]}"
        skip_modules = " ".join([f"-skip {m}" for m in self.config.skip_modules])

        # Get version-specific configuration
        version_config = self.config.get_version_config()
        cxx_std = version_config.get("c++std", "c++14")

        # Build type option
        build_type_opt = "-debug" if self.config.build_type == "debug" else "-release"

        # Generate script content
        script_content = f'''@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

echo ============================================
echo Qt for HarmonyOS Build Script
echo Qt Version: {self.config.qt_version}
echo Generated by qtohos-installer
echo ============================================
echo.

REM Reset PATH to avoid MSVC pollution and other MinGW interference
set "PATH=C:\\Windows\\System32;C:\\Windows"

REM Clear MAKEFLAGS to prevent sh.exe dependency from other MinGW
set "MAKEFLAGS="
set "MFLAGS="
set "SHELL=cmd.exe"

REM Add llvm-mingw-ucrt FIRST - provides clang/clang++ and mingw32-make for host tools
set "MINGW_BIN={mingw_bin}"
if exist "%MINGW_BIN%" set "PATH=%PATH%;%MINGW_BIN%"
if exist "%MINGW_BIN%" echo [OK] MinGW (llvm-mingw): %MINGW_BIN%
if not exist "%MINGW_BIN%" echo [ERROR] MinGW path not found: %MINGW_BIN%
if not exist "%MINGW_BIN%" exit /b 1

REM Add Perl (only for perl, not for GCC)
set "PERL_BIN={perl_bin}"
if exist "%PERL_BIN%" set "PATH=%PATH%;%PERL_BIN%"
if exist "%PERL_BIN%" echo [OK] Perl: %PERL_BIN%
if not exist "%PERL_BIN%" echo [ERROR] Perl path not found: %PERL_BIN%
if not exist "%PERL_BIN%" exit /b 1

REM Add LLVM for OHOS cross-compile
set "LLVM_BIN={llvm_bin}"
if exist "%LLVM_BIN%" set "PATH=%PATH%;%LLVM_BIN%"
if exist "%LLVM_BIN%" echo [OK] LLVM: %LLVM_BIN%
if not exist "%LLVM_BIN%" echo [WARN] LLVM path not found: %LLVM_BIN%

REM Set environment variables
set "NATIVE_OHOS_SDK={self.config.harmony_sdk_path}\\native"
set "OHOS_SDK_SYSROOT={self.config.harmony_sdk_path}\\native\\sysroot"
set "LLVM_INSTALL_DIR={llvm_bin}\\.."
set "OHOS_SDK_ROOT={self.config.harmony_sdk_path}"
set "OHOS_TARGET_ARCH={self.config.architecture}"

echo.
echo Environment:
echo   NATIVE_OHOS_SDK: %NATIVE_OHOS_SDK%
echo   OHOS_TARGET_ARCH: %OHOS_TARGET_ARCH%
echo.

REM Check compilers with full path verification
echo Compiler check:
echo.

REM Show ALL clang.exe found in PATH (for diagnosis)
echo All clang.exe found in PATH:
where clang.exe 2>nul
echo.

where cl.exe >nul 2>&1
if %errorlevel% equ 0 echo [WARN] MSVC cl.exe found in PATH - may cause issues
if %errorlevel% neq 0 echo [OK] MSVC cl.exe not found

REM Get first clang.exe (llvm-mingw provides clang as g++ wrapper)
set "CLANG_PATH="
for /f "tokens=*" %%i in ('where clang.exe 2^>nul') do (
    if not defined CLANG_PATH set "CLANG_PATH=%%i"
)
if defined CLANG_PATH echo [OK] Clang found: %CLANG_PATH%
if not defined CLANG_PATH echo [ERROR] Clang not found
if not defined CLANG_PATH exit /b 1

REM Verify clang is from llvm-mingw-ucrt
echo %CLANG_PATH% | findstr /i "llvm-mingw" >nul
if %errorlevel% equ 0 echo [OK] Clang is from llvm-mingw

REM Get first clang++.exe
set "CLANGPP_PATH="
for /f "tokens=*" %%i in ('where clang++.exe 2^>nul') do (
    if not defined CLANGPP_PATH set "CLANGPP_PATH=%%i"
)
if defined CLANGPP_PATH echo [OK] Clang++ found: %CLANGPP_PATH%
if not defined CLANGPP_PATH echo [ERROR] Clang++ not found
if not defined CLANGPP_PATH exit /b 1

REM Unset all compiler and Qt environment variables before configure
REM This prevents cached compiler paths from interfering
set "QMAKESPEC="
set "XQMAKESPEC="
set "QMAKEPATH="
set "QMAKEFEATURES="
set "LD="
set "AR="
set "NM="
set "STRIP="
set "OBJCOPY="
set "OBJDUMP="
set "RC="
set "WINDRES="
set "CFLAGS="
set "CXXFLAGS="
set "LDFLAGS="
set "CPPFLAGS="
set "QMAKE_CC="
set "QMAKE_CXX="
set "QMAKE_LINK="
set "QMAKE_AR="
REM Also unset potential MinGW paths from other installations
set "MINGW_HOME="
set "MSYSTEM="
set "MSYSTEM_PREFIX="
set "GITHUB_PATH="
set "GIT_INSTALL_ROOT="

echo.
echo ============================================

REM Create build directory
set "BUILD_DIR={self.build_dir}"
if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"

REM Clean old config cache to force compiler redetection
REM This prevents using cached compiler paths from previous runs
if exist "%BUILD_DIR%\\config.cache" del /f "%BUILD_DIR%\\config.cache"
if exist "%BUILD_DIR%\\config.log" del /f "%BUILD_DIR%\\config.log"
if exist "%BUILD_DIR%\\config.summary" del /f "%BUILD_DIR%\\config.summary"
if exist "%BUILD_DIR%\\.qmake.super" del /f "%BUILD_DIR%\\.qmake.super"
if exist "%BUILD_DIR%\\bin" rd /s /q "%BUILD_DIR%\\bin"
if exist "%BUILD_DIR%\\mkspecs" rd /s /q "%BUILD_DIR%\\mkspecs"
if exist "%BUILD_DIR%\\include" rd /s /q "%BUILD_DIR%\\include"
if exist "%BUILD_DIR%\\lib" rd /s /q "%BUILD_DIR%\\lib"
if exist "%BUILD_DIR%\\src" rd /s /q "%BUILD_DIR%\\src"
if exist "%BUILD_DIR%\\plugins" rd /s /q "%BUILD_DIR%\\plugins"
if exist "%BUILD_DIR%\\Makefile" del /f "%BUILD_DIR%\\Makefile"
if exist "%BUILD_DIR%\\qtbase" rd /s /q "%BUILD_DIR%\\qtbase"
if exist "C:\\code\\config.tests" rd /s /q "C:\\code\\config.tests"
REM Clean source tree cache files
if exist "{self.config.qt_source_path}\\qtbase\\.qmake.stash" del /f "{self.config.qt_source_path}\\qtbase\\.qmake.stash"
if exist "{self.config.qt_source_path}\\qtbase\\config.summary" del /f "{self.config.qt_source_path}\\qtbase\\config.summary"
REM Clean qmake bootstrap directory (contains cached compiler paths)
if exist "{self.config.qt_source_path}\\qtbase\\qmake\\Makefile" del /f "{self.config.qt_source_path}\\qtbase\\qmake\\Makefile"
if exist "{self.config.qt_source_path}\\qtbase\\qmake\\.obj" rd /s /q "{self.config.qt_source_path}\\qtbase\\qmake\\.obj"
if exist "{self.config.qt_source_path}\\qtbase\\src\\corelib\\global\\qconfig.cpp" del /f "{self.config.qt_source_path}\\qtbase\\src\\corelib\\global\\qconfig.cpp"

REM Run configure
echo.
echo [Configure] Starting...
echo.

pushd "%BUILD_DIR%"

call "{configure_script}" -v -platform win32-clang-g++ -xplatform ohos-clang -device-option CROSS_COMPILE=%LLVM_INSTALL_DIR%\\bin -prefix "{device_prefix}" -extprefix "{self.config.install_path}" -opensource -confirm-license {build_type_opt} -no-use-gold-linker {skip_modules} -nomake tests -nomake examples -no-gcc-sysroot -c++std {cxx_std} -ohos-arch {self.config.architecture}

if %errorlevel% neq 0 echo.
if %errorlevel% neq 0 echo [ERROR] Configure failed with code %errorlevel%
if %errorlevel% neq 0 popd
if %errorlevel% neq 0 exit /b 1

echo.
echo [OK] Configure completed successfully
echo.

REM Build
echo [Build] Starting with {self.config.parallel_jobs} parallel jobs...
echo.

REM Force using cmd.exe instead of sh.exe to avoid Git Bash interference
set "SHELL=cmd.exe"
mingw32-make SHELL=cmd.exe -j{self.config.parallel_jobs}

if %errorlevel% neq 0 echo.
if %errorlevel% neq 0 echo [ERROR] Build failed with code %errorlevel%
if %errorlevel% neq 0 popd
if %errorlevel% neq 0 exit /b 1

echo.
echo [OK] Build completed successfully
echo.

REM Install
echo [Install] Starting...
echo.

mingw32-make install

if %errorlevel% neq 0 echo.
if %errorlevel% neq 0 echo [ERROR] Install failed with code %errorlevel%
if %errorlevel% neq 0 popd
if %errorlevel% neq 0 exit /b 1

popd

REM Copy runtime DLLs
echo.
echo [Copy] Copying runtime dependencies...
for %%d in (libstdc++-6.dll libgcc_s_seh-1.dll libwinpthread-1.dll) do if exist "%MINGW_BIN%\\%%d" copy /y "%MINGW_BIN%\\%%d" "{self.config.install_path}\\bin\\" >nul
for %%d in (libstdc++-6.dll libgcc_s_seh-1.dll libwinpthread-1.dll) do if exist "%MINGW_BIN%\\%%d" echo [OK] Copied: %%d

echo.
echo ============================================
echo [SUCCESS] Build completed!
echo Install path: {self.config.install_path}
echo ============================================

if exist "{self.config.install_path}\\bin\\qmake.exe" echo.
if exist "{self.config.install_path}\\bin\\qmake.exe" echo Qt version:
if exist "{self.config.install_path}\\bin\\qmake.exe" "{self.config.install_path}\\bin\\qmake.exe" -query QT_VERSION

exit /b 0
'''

        # Write script to file
        script_path = self.build_dir.parent / "build_qt_ohos.bat"
        script_path.write_text(script_content, encoding="utf-8")
        self.build_script_path = script_path

        self.console.print(f"[green]✓ Generated build script: {script_path}[/green]")
        self.logger.info(f"Generated build script: {script_path}")

        return script_path
    
    def generate_configure_command(self) -> List[str]:
        """
        Generate configure command for Qt

        Returns:
            Configure command as list of strings
        """
        self.console.print("\n[bold cyan]Generating configure command...[/bold cyan]")

        # Get version-specific configuration
        version_config = self.config.get_version_config()

        # Base configure command - use qtbase/configure.bat directly (no -top-level)
        if is_windows():
            configure_script = self.config.qt_source_path / "qtbase" / "configure.bat"
            if not configure_script.exists():
                configure_script = self.config.qt_source_path / "configure.bat"
            cmd = [str(configure_script)]
        else:
            configure_script = self.config.qt_source_path / "configure"
            cmd = [str(configure_script)]

        # Add common options
        cmd.extend([
            "-v",  # Verbose output
        ])

        # CRITICAL: Specify host platform to use MinGW for building host tools (qmake, etc.)
        # Without this, Qt defaults to nmake (MSVC) which will fail
        if is_windows():
            cmd.extend(["-platform", "win32-g++"])

        # Cross-compilation target platform
        cmd.extend(["-xplatform", "ohos-clang"])

        cmd.extend([
            "-opensource",
            "-confirm-license",
            "-no-use-gold-linker",
            "-no-gcc-sysroot",
        ])

        # Qt version-specific architecture option
        # Use -ohos-arch for all versions (matches working manual workflow)
        cmd.extend(["-ohos-arch", self.config.architecture])

        # Add CROSS_COMPILE device option for cross-compilation
        if is_windows():
            llvm_dir = self.env_manager.env_vars.get("LLVM_INSTALL_DIR", "")
            if llvm_dir:
                cmd.extend(["-device-option", f"CROSS_COMPILE={llvm_dir}/bin"])

        # C++ standard
        cxx_std = version_config.get("c++std", "c++14")
        cmd.extend(["-c++std", cxx_std])

        cmd.extend([
            "-nomake", "examples",
            "-nomake", "tests",
        ])

        # Build type
        if self.config.build_type == "debug":
            cmd.append("-debug")
        elif self.config.build_type == "release":
            cmd.append("-release")
        else:  # release-with-debug-info
            cmd.extend(["-release", "-force-debug-info"])

        # Installation prefix
        # For HarmonyOS, we use two prefixes:
        # -prefix: location on device (e.g., /data/storage/el1/bundle/libs/arm64)
        # -extprefix: external prefix (actual installation location)

        device_prefix = f"/data/storage/el1/bundle/libs/{self.config.architecture.split('-')[0]}"
        cmd.extend([
            "-prefix", device_prefix,
            "-extprefix", str(self.config.install_path),
        ])

        # Skip modules
        for module in self.config.skip_modules:
            cmd.extend(["-skip", module])

        # Add any extra version-specific options
        extra_options = version_config.get("extra_configure_options", [])
        cmd.extend(extra_options)

        # Display command
        self.console.print("\n[bold]Configure command:[/bold]")
        cmd_str = " ".join(cmd)
        self.console.print(Panel(cmd_str, border_style="cyan"))

        return cmd
    
    def configure_qt(self) -> Tuple[int, str, str]:
        """
        Run Qt configure
        
        Returns:
            Tuple of (exit_code, stdout, stderr)
        """
        self.console.print("\n[bold cyan]Configuring Qt...[/bold cyan]")
        self.logger.info("Starting Qt configuration")
        
        cmd = self.generate_configure_command()
        env = self.env_manager.get_build_environment()
        self._print_windows_path_check(env)
        self._print_compiler_detection(env)

        # Run configure
        exit_code, stdout, stderr = run_command(
            cmd,
            cwd=self.build_dir,
            env=env,
            capture_output=False,
            logger=self.logger
        )
        
        if exit_code == 0:
            self.console.print("\n[green]✓ Qt configuration completed successfully[/green]")
            self.logger.info("Qt configuration completed successfully")
        else:
            self.console.print(f"\n[red]✗ Qt configuration failed with code: {exit_code}[/red]")
            self.logger.error(f"Qt configuration failed with code: {exit_code}")
        
        return exit_code, stdout, stderr

    def _print_windows_path_check(self, env: dict) -> None:
        """
        Print Windows build environment and verify required PATH entries.
        """
        if not is_windows():
            return

        self.console.print("\n[bold cyan]Build environment (Windows) before configure:[/bold cyan]")
        self.console.print(f"  [cyan]MINGW_ROOT[/cyan]: {env.get('MINGW_ROOT', '(not set)')}")
        self.console.print(f"  [cyan]PERL_ROOT[/cyan]: {env.get('PERL_ROOT', '(not set)')}")
        self.console.print(f"  [cyan]QMAKESPEC[/cyan]: {env.get('QMAKESPEC', '(not set)')}")

        path_value = env.get("PATH", "")
        path_entries = [item for item in path_value.split(";") if item]
        normalized_entries = {item.rstrip("\\/").lower() for item in path_entries}

        required_paths: List[Path] = []

        mingw_bin_raw = env.get("MINGW_ROOT")
        if mingw_bin_raw:
            mingw_bin = Path(mingw_bin_raw)
            required_paths.extend([mingw_bin, mingw_bin.parent])

        perl_bin_raw = env.get("PERL_ROOT")
        if perl_bin_raw:
            perl_bin = Path(perl_bin_raw)
            if perl_bin.name.lower() != "bin":
                perl_bin = perl_bin / "bin"
            perl_root = perl_bin.parent
            strawberry_root = perl_root.parent
            required_paths.extend([
                perl_bin,
                strawberry_root / "c" / "bin",
                perl_root / "site" / "bin",
            ])

        # Keep order and remove duplicates.
        deduped_required = []
        seen = set()
        for item in required_paths:
            key = str(item).rstrip("\\/").lower()
            if key and key not in seen:
                seen.add(key)
                deduped_required.append(str(item))

        if deduped_required:
            self.console.print("  [bold]Required PATH entries:[/bold]")
            for item in deduped_required:
                exists_in_path = item.rstrip("\\/").lower() in normalized_entries
                symbol = "[green]✓[/green]" if exists_in_path else "[red]✗[/red]"
                self.console.print(f"    {symbol} {item}")
        else:
            self.console.print("  [yellow]No required Windows tool roots derived from config.[/yellow]")

    def _print_compiler_detection(self, env: dict) -> None:
        """
        Print compiler detection status before configure.

        Verifies that:
        - MSVC cl.exe is NOT in PATH (should not be found)
        - GCC IS in PATH (should be found on Windows)
        - Clang IS in PATH (should be found)
        """
        if not is_windows():
            return

        self.console.print("\n[bold cyan]Compiler detection before configure:[/bold cyan]")

        path_value = env.get("PATH", "")

        # Check for MSVC cl.exe (should NOT be found)
        cl_path = shutil.which("cl.exe", path=path_value)
        if cl_path:
            self.console.print(f"  [red]✗ MSVC cl.exe found (PROBLEM): {cl_path}[/red]")
            self.console.print("    [yellow]This may cause configure to select MSVC instead of MinGW[/yellow]")
        else:
            self.console.print("  [green]✓ MSVC cl.exe not found (correct)[/green]")

        # Check for GCC (SHOULD be found on Windows)
        gcc_path = shutil.which("gcc.exe", path=path_value)
        if gcc_path:
            self.console.print(f"  [green]✓ GCC found: {gcc_path}[/green]")
        else:
            self.console.print("  [red]✗ GCC not found (PROBLEM)[/red]")
            self.console.print("    [yellow]MinGW should be in PATH for building host tools[/yellow]")

        # Check for Clang (SHOULD be found)
        clang_path = shutil.which("clang.exe", path=path_value)
        if clang_path:
            self.console.print(f"  [green]✓ Clang found: {clang_path}[/green]")
        else:
            self.console.print("  [yellow]⚠ Clang not found[/yellow]")
            self.console.print("    [yellow]Clang is needed for cross-compiling to HarmonyOS[/yellow]")

        self.logger.info(
            "Compiler detection - cl.exe: %s, gcc: %s, clang: %s",
            cl_path or "(not found)",
            gcc_path or "(not found)",
            clang_path or "(not found)",
        )

    def build_qt(self) -> Tuple[int, str, str]:
        """
        Build Qt (make)
        
        Returns:
            Tuple of (exit_code, stdout, stderr)
        """
        self.console.print("\n[bold cyan]Building Qt...[/bold cyan]")
        self.console.print(
            f"[yellow]This may take a long time (parallel jobs: {self.config.parallel_jobs})[/yellow]"
        )
        self.logger.info(f"Starting Qt build with {self.config.parallel_jobs} parallel jobs")
        
        env = self.env_manager.get_build_environment()
        self._print_make_tool_path(env)
        
        # Make command
        cmd = [self.make_cmd, f"-j{self.config.parallel_jobs}"]
        
        # Run make
        exit_code, stdout, stderr = run_command(
            cmd,
            cwd=self.build_dir,
            env=env,
            capture_output=False,
            logger=self.logger
        )
        
        if exit_code == 0:
            self.console.print("\n[green]✓ Qt build completed successfully[/green]")
            self.logger.info("Qt build completed successfully")
        else:
            self.console.print(f"\n[red]✗ Qt build failed with code: {exit_code}[/red]")
            self.logger.error(f"Qt build failed with code: {exit_code}")
        
        return exit_code, stdout, stderr
    
    def install_qt(self) -> Tuple[int, str, str]:
        """
        Install Qt (make install)
        
        Returns:
            Tuple of (exit_code, stdout, stderr)
        """
        self.console.print("\n[bold cyan]Installing Qt...[/bold cyan]")
        self.logger.info("Starting Qt installation")
        
        env = self.env_manager.get_build_environment()
        self._print_make_tool_path(env)
        
        # Make install command
        cmd = [self.make_cmd, "install"]
        
        # Run make install
        exit_code, stdout, stderr = run_command(
            cmd,
            cwd=self.build_dir,
            env=env,
            capture_output=False,
            logger=self.logger
        )
        
        if exit_code == 0:
            self.console.print("\n[green]✓ Qt installation completed successfully[/green]")
            self.logger.info("Qt installation completed successfully")
            
            # Verify installation
            self._verify_installation()
        else:
            self.console.print(f"\n[red]✗ Qt installation failed with code: {exit_code}[/red]")
            self.logger.error(f"Qt installation failed with code: {exit_code}")
        
        return exit_code, stdout, stderr

    def _print_make_tool_path(self, env: dict) -> None:
        """Print currently resolved make tool path before running make commands."""
        self.console.print("\n[bold cyan]Resolving make tool...[/bold cyan]")
        configured_make = str(self.config.make_path) if self.config.make_path else "(not configured)"
        resolved_make = shutil.which(self.make_cmd, path=env.get("PATH"))
        self.console.print(f"  [cyan]Configured make_path[/cyan]: {configured_make}")
        self.console.print(f"  [cyan]make command[/cyan]: {self.make_cmd}")
        self.console.print(f"  [cyan]Resolved path[/cyan]: {resolved_make or '(not found in PATH)'}")
        self.logger.info(
            "Make tool resolution - configured: %s, command: %s, resolved: %s",
            configured_make,
            self.make_cmd,
            resolved_make or "(not found in PATH)",
        )
    
    def _verify_installation(self) -> None:
        """Verify Qt installation"""
        self.console.print("\n[bold cyan]Verifying installation...[/bold cyan]")
        
        # Check for qmake
        qmake_path = self.config.install_path / "bin" / "qmake"
        if is_windows():
            qmake_path = qmake_path.with_suffix(".exe")
        
        if qmake_path.exists():
            self.console.print(f"[green]✓ qmake found: {qmake_path}[/green]")
            
            # Get Qt version
            try:
                result = run_command(
                    [str(qmake_path), "-query", "QT_VERSION"],
                    capture_output=True,
                    logger=self.logger
                )
                if result[0] == 0:
                    qt_version = result[1].strip()
                    self.console.print(f"[green]  Qt version: {qt_version}[/green]")
            except Exception:
                pass
        else:
            self.console.print(f"[yellow]⚠ qmake not found at expected location[/yellow]")
        
        # Check for libraries
        lib_dir = self.config.install_path / "lib"
        if lib_dir.exists():
            libs = list(lib_dir.glob("*.so")) if not is_windows() else list(lib_dir.glob("*.dll"))
            self.console.print(f"[green]✓ Found {len(libs)} libraries[/green]")
        else:
            self.console.print(f"[yellow]⚠ Library directory not found[/yellow]")
    
    def build_all(self) -> bool:
        """
        Run complete build process

        Returns:
            True if all steps successful, False otherwise
        """
        self.console.print("\n" + "=" * 60)
        self.console.print("[bold cyan]Starting Qt Build Process[/bold cyan]")
        self.console.print("=" * 60)

        # Step 1: Prepare build directory
        if not self.prepare_build_directory():
            return False

        # On Windows, use batch script to avoid environment inheritance issues
        if is_windows():
            return self._build_with_script()

        # On Unix, use direct subprocess calls
        # Step 2: Configure
        exit_code, _, _ = self.configure_qt()
        if exit_code != 0:
            return False

        # Step 3: Build
        exit_code, _, _ = self.build_qt()
        if exit_code != 0:
            return False

        # Step 4: Install
        exit_code, _, _ = self.install_qt()
        if exit_code != 0:
            return False

        self.console.print("\n" + "=" * 60)
        self.console.print("[bold green]✓ Qt Build Process Completed Successfully[/bold]")
        self.console.print("=" * 60)

        return True

    def _build_with_script(self) -> bool:
        """
        Build Qt using generated batch script (Windows only).
        This avoids environment variable inheritance issues with subprocess.

        Returns:
            True if successful, False otherwise
        """
        self.console.print("\n[bold cyan]Building Qt with batch script (Windows)...[/bold cyan]")

        # Generate the build script
        script_path = self.generate_build_script()

        self.console.print(f"\n[yellow]Running build script: {script_path}[/yellow]")
        self.console.print("[yellow]This may take a long time...[/yellow]")
        self.logger.info(f"Executing build script: {script_path}")

        # Run the batch script
        try:
            # Use subprocess to run the batch script
            # Pass MINIMAL environment - batch script will set what it needs
            import subprocess

            # Start with a clean environment to avoid Git Bash / other MinGW interference
            clean_env = {
                "PATH": "C:\\Windows\\System32;C:\\Windows",
                "SYSTEMROOT": os.environ.get("SYSTEMROOT", "C:\\Windows"),
                "TEMP": os.environ.get("TEMP", ""),
                "TMP": os.environ.get("TMP", ""),
                "USERPROFILE": os.environ.get("USERPROFILE", ""),
                "HOMEDRIVE": os.environ.get("HOMEDRIVE", ""),
                "HOMEPATH": os.environ.get("HOMEPATH", ""),
                "COMSPEC": os.environ.get("COMSPEC", "C:\\Windows\\System32\\cmd.exe"),
                "PATHEXT": os.environ.get("PATHEXT", ".COM;.EXE;.BAT;.CMD"),
            }

            result = subprocess.run(
                [str(script_path)],
                cwd=self.build_dir.parent,
                shell=True,
                env=clean_env
            )

            if result.returncode == 0:
                self.console.print("\n" + "=" * 60)
                self.console.print("[bold green]✓ Qt Build Process Completed Successfully[/bold]")
                self.console.print("=" * 60)
                self._verify_installation()
                return True
            else:
                self.console.print(f"\n[red]✗ Build failed with code: {result.returncode}[/red]")
                self.logger.error(f"Build script failed with code: {result.returncode}")
                return False

        except Exception as e:
            self.console.print(f"\n[red]✗ Failed to run build script: {e}[/red]")
            self.logger.error(f"Failed to run build script: {e}")
            return False
